STATEMENTS ::= (ASSIGNMENT | LOOP_ASSIGNMENT)*

ASSIGNMENT ::= VAR ASSIGN EXPR END_OF_STATEMENT
LOOP_ASSIGNMENT ::= LOOP OPERAND OPEN_CURL ASSIGNMENT CLOSE_CURL

EXPR ::= ADD_EXPR

ADD_EXPR ::= MUL_EXPR (ADD_OR_SUB MUL_EXPR)*
MUL_EXPR ::= OPERAND (MUL_OR_DIV OPERAND)*
OPERAND ::= NUM | VAR

VAR ::= 'r10' | 'r11' | 'r12' | 'r13'
NUM ::= ('0'|'1'|'2'|'3'|'4'|'5'|'6'|'7'|'8'|'9')+
ADD_OR_SUB ::= '+' | '-'
MUL_OR_DIV ::= '*' | '/'
CLOSE_CURL ::= '}'
OPEN_CURL ::= '{'
LOOP ::= 'loop'
END_OF_STATEMENT ::= ';'
ASSIGN ::= '='
